### ISSUE TITLE
examples needed

### ISSUE THREAD

**Issue by benoitc** [barrel-db/rebar3_elixir_compile#3]
we need some examples and a `Getting Started` doc

**Comment by sivsushruth** [comment]
add example. Need a getting started doc @benoitc

**Comment by waisbrot** [comment]
What does `elixir_opts` do? Does the `{compile, {ex, compile}}` hook compile all Elixir apps?

**Comment by benoitc** [comment]
@waisbrot elixir_opts allow you to set the paths to the elixir installation (bin and libs). Otherwise it is discovered in the PATH.

The compile hook will compile all the elixir apps and their dependencies. Elixir apps are fetched via the `deps`.

**Comment by benoitc** [comment]
done. Thanks!
