### ISSUE TITLE
support for releases?

### ISSUE THREAD

**Issue by benoitc** [barrel-db/rebar3_elixir_compile#7]
Does the current implementation supports release? what happen when we run `rebar3 release` ? An example should be provided.

**Comment by sivsushruth** [comment]
@benoitc It does support releases also, please include elixir in your app.src

**Comment by sivsushruth** [comment]
Let me know if this does not work for you @benoitc . Closing for now.

**Comment by benoitc** [comment]
will close it once tested :) please provides an example

**Comment by benoitc** [comment]
latest commit fixed it. Thanks!
